services:
  - type: web
    name: shekhar-app
    env: node
    buildCommand: |
      npm install --prefix backend
      npm install --prefix frontend
      npm run build --prefix frontend
    startCommand: node backend/server.js
    autoDeploy: true
